/* ===========================================================================
   SITE DATA — edit these freely. Used by main.js to build page sections.
   =========================================================================== */
const TESTIMONIALS = [
  {q:"They treated our first home like it was their own. Patient, honest, and always a step ahead.", who:"— Former Customer"},
  {q:"We sold above asking and closed without a single surprise. The communication was incredible.", who:"— Former Customer"},
  {q:"More than agents — they felt like family who genuinely wanted us to be happy in our new home.", who:"— Former Customer"}
];

const RESIDENTIAL_LISTINGS = [
  {city:"Gardena, CA", desc:"2 bed · 2.5 bath · 1,281 sqft — Listed at $735K, offering modern living in a prime location. Conveniently close to schools, shopping, dining, and everyday amenities.", tag:"For Sale", img:"gardena.png", price:"$735K", detail:"Welcome to modern living in the heart of Gardena. This sleek 2-bedroom, 2.5-bathroom home offers 1,281 square feet of thoughtfully designed space, perfect for those seeking comfort and convenience. Located in a prime neighborhood, you're just moments away from top schools, shopping centers, and dining destinations. Listed at $752K, this is an incredible opportunity to own a stylish home in one of Southern California's most accessible communities.."},
  {city:"Chino, CA", desc:"4 bed · 3.5 bath · 1,930 sqft — Newly built home, a cozy modern estate near top-rated schools and great social hubs.", tag:"In Escrow", img:"nesta.png", price:"$855K", detail:"Discover this stunning newly built home nestled in one of Chino's most sought-after neighborhoods. Offering 4 bedrooms and 3.5 bathrooms across 1,930 square feet, this modern estate blends contemporary design with cozy charm. Families will love the proximity to top-rated schools and vibrant social hubs, making it the perfect place to put down roots and build lasting memories."},
  {city:"Fontana, CA", desc:"3 bed · 3 bath · 1,677 sqft — Great recently built townhouse, providing great views of California and the San Bernardino Valley.", tag:"Sold", img:"townhouse.png", price:"$532K", detail:"Experience breathtaking views of California and the San Bernardino Valley from this recently built townhouse in Fontana. With 3 bedrooms, 3 bathrooms, and 1,677 square feet of living space, this home offers a great blend of style and functionality. Whether you're entertaining guests or enjoying a quiet evening, the stunning natural backdrop makes every moment feel extraordinary."},
  {city:"Diamond Bar, CA", desc:"5 bed · 4 bath · 3,228 sqft — Big, spacious house with great natural lighting in a prime educational location.", tag:"Sold", img:"diamond bar.png", price:"$1.45M", detail:"Space, light, and location — this Diamond Bar gem has it all. Boasting 5 bedrooms, 4 bathrooms, and an impressive 3,228 square feet, this spacious home is flooded with natural light throughout. Situated in one of the area's premier educational corridors, it's ideal for growing families who value both room to breathe and access to excellent schools. A rare find at this size and caliber."},
  {city:"Eastvale, CA", desc:"3 bed · 3 bath · 2,655 sqft — Classic craftsman, fully reimagined house with an amazing naturally designed pool.", tag:"Sold", img:"eastvale.png", price:"$950K", detail:"This classic Craftsman home in Eastvale has been fully reimagined for modern living while preserving its timeless character. With 3 bedrooms, 3 bathrooms, and 2,655 square feet, there's no shortage of space to live and entertain. The crown jewel is the beautifully designed pool, crafted with natural materials that seamlessly blend with the outdoor landscape — your own private retreat right at home."},
  {city:"Fullerton, CA", desc:"4 bed · 3 bath · 2,400 sqft — Big bright house that's almost impossible to find in Southern Californiacan.", tag:"In Escrow", img:"fullertonn.png", price:"$1.37M", detail:"ig, bright, and truly one of a kind — this Fullerton home is the kind of property that rarely comes to market in Southern California. Offering 4 bedrooms, 3 bathrooms, and 2,400 square feet of sun-drenched living space, every room feels open and inviting. Whether you're a growing family or simply looking for more room to live life to the fullest, this home delivers in every way."}
];

const COMMERCIAL_LISTINGS = [
  {city:"Burbank, CA", desc:"Class A office building fully leased to Walt Disney Enterprises, located in the Burbank Media District.", tag:"Fully Leased", img:"one.jpeg", price:"$32M", detail:"A Class A office investment in the Burbank Media District, fully leased to Walt Disney Enterprises since 1991. The 115,130 sq ft building sits on a 1.26-acre site, built in 1991 and renovated in 2004. Features a 3.5/1,000 SF parking ratio and an S&amp;P A-rated tenant, with convenient proximity to Disney's headquarters campus."},  {city:"Anaheim", desc:"Modern cozy office-suite building in Central Anaheim.", tag:"FULLY LEASED", img:"com2.png", detail:"A clean, modern two-story office building in central Anaheim, configured as a set of efficient professional suites ideal for small businesses, medical, or service tenants. The property offered a bright window-lined facade, a welcoming central entrance, and a practical floor plan that maximized usable space. Located minutes from major thoroughfares with convenient parking, it presented a low-maintenance, income-ready asset — now sold and under new ownership."},
  {city:"Las Vegas, NV", desc:"232-unit garden apartment community with completed renovations and condo conversion permits approved.", tag:"Note Purchase", img:"two.jpeg", price:"$19.5M", detail:"A non-performing note purchase opportunity on a 232-unit, 2-story garden apartment community in Las Vegas. The property spans 14.99 acres across 29 residential buildings and 2 common area buildings, with 240,352 SF net rentable area. Built in 1984 and renovated in 2006–2007, each unit is 2 bed/2 bath at 1,200 SF with 380 parking spaces (1.64/unit). Renovation is complete and permits have been approved for immediate condo sales, with individual APNs assigned to each unit."},
  {city:"CA / NV Portfolio", desc:"A portfolio of 22 non-performing SBA notes secured by gas stations and auto service properties across California and Nevada.", tag:"Note Purchase", img:"three.jpeg", price:"~$32M", detail:"A non-performing SBA note purchase portfolio of gas station and auto service properties across CA and NV:\n• Santa Paula, CA – Sprint gas station (~$1.1M)\n• Newberry Springs, CA – Texaco (~$1.4M)\n• El Monte, CA – ARCO gas station (~$3M)\n• Vernon, CA – ARCO gas station (~$2.2M)\n• Wofford Heights, CA – Chevron (~$356K)\n• Simi Valley, CA – Alliance + Auto Service (~$306K)\n• Ojai, CA – 76 + Auto Service (~$987K)\n• Oxnard, CA – Alliance + Carwash (~$1.3M)\n• El Monte, CA – ARCO gas station (~$495K)\n• Corona, CA – Valero + Auto Service (~$1.3M)\n• Barstow, CA – Valero gas station (~$1.1M)\n• Sherman Oaks, CA – Condor gas station (~$1.2M)\n• Las Vegas, NV – ARCO gas station (~$4.2M)\n• Simi Valley, CA – Alliance gas station (~$1.1M)\n• Hemet, CA – Chevron + Carwash (~$2.6M)\n• Pomona, CA – ARCO gas station (~$866K)\n• Los Angeles, CA – Tire/Auto service (~$99K)\n• North Hollywood, CA – 76 + Auto Service (~$1.2M)\n• Orange, CA – 76 + Auto Service (~$1.3M)\n• Covina, CA – ARCO + Auto Service (~$2M)\n• Los Angeles, CA – ARCO gas station (~$2.1M)\n• Azusa, CA – Shell + Subway + Auto Service (~$2.1M)"},
  {city:"Los Angeles, CA", desc:"Five-story retail/office building occupied by California International University, located in the Wilshire corridor of Los Angeles.", tag:"Retail/Office", img:"four.jpeg", price:"~$29M", detail:"A five-story concrete brick retail/office building in the Wilshire corridor of Los Angeles, occupied by California International University. The property totals 71,969 sq ft gross building area on a 31,741 sq ft corner lot, zoned C4-2. Built in 1968, the building features a rectangular site shape with an appraised value of $28,800,000 as of February 2017."},
  {city:"Los Angeles, CA", desc:"10-unit apartment building in prime Koreatown with strong rent upside and future development potential.", tag:"Multifamily", img:"five.jpeg", price:"$2.2M", detail:"A 10-unit, two-story apartment building in the Koreatown neighborhood of Los Angeles, built in 1951. The property sits on a 9,234 SF corner lot zoned LAR4, with 7,992 sq ft of rentable space. Unit mix: 2 one-bedroom/one-bath and 8 two-bedroom/one-bath units. Features a gated center courtyard, 8 parking spaces, and individually metered electric and gas. Current CAP rate of 4.65% with pro forma upside to 6.67%. Walking distance to the Wilshire/Vermont Metro station with access to the Purple and Red Lines."},
  {city:"Los Angeles, CA", desc:"16-story Class A government building available as a sale-leaseback opportunity in Downtown Los Angeles.", tag:"Sale-Leaseback", img:"six.jpeg", price:"", detail:"A Class A government building sale-leaseback opportunity in Downtown Los Angeles. The Ronald Reagan Building spans 781,019 sq ft across 16 floors on a 2.60-acre site, built in 1990. Features 120 parking spaces, 24/7 building access, bus line access, and is LEED registered. Financing available as cash or cash to new loan."},
  {city:"Pittsburgh, PA", desc:"Iconic 64-story Class A office tower anchored by major Fortune 500 tenants including UPMC, US Steel, and PNC Bank.", tag:"Office Tower", img:"seven.jpeg", price:"$290M", detail:"A landmark 64-story, 2,340,000 sq ft Class A office tower in Downtown Pittsburgh. Over 70% leased to Fortune 500 tenants with 'A' credit ratings, including University of Pittsburgh Medical Center (HQ), US Steel, PNC Bank Corp., and Eckert Seamans. Long-term leases extending to approximately 2030. Major renovation completed 1999–2005. Current occupancy of 95.5% with a 10-year average of 93.6%. Pittsburgh's commercial real estate market is ranked #1 by Moody's Investors Service across 60 metropolitan markets."},
  {city:"West Los Angeles, CA", desc:"Distressed Class A office building purchase opportunity with significant vacancy upside in West Los Angeles.", tag:"Distressed Office", img:"eight.jpeg", price:"", detail:"A 3-story, 81,537 sq ft Class A office building in West Los Angeles, built in 1981 and renovated in 2009. Situated on a 0.77-acre site with a 2.40/1,000 SF parking ratio. Current occupancy is 65.9% with 57,691 SF available, offering significant lease-up upside. Multi-tenant, non-owner occupied. Amenities include an atrium, bus line access, on-site management, and on-site property management."},
  {city:"Los Angeles, CA", desc:"16-unit residential condo building in Koreatown featuring a mix of 2 and 3-bedroom units with premium finishes and mezzanine layouts.", tag:"Residential Condo", img:"nine.jpeg", price:"~$10.6M", detail:"The Concord is a 16-unit condo building in the Koreatown neighborhood of Los Angeles, totaling 21,015 sq ft across 4 residential floors with underground and first-floor parking. Unit mix includes 2 Bed/2 Bath and 3 Bed/2 Bath configurations, ranging from approximately 1,256–1,432 sq ft of living space. Select units feature a den, mezzanine, and private deck. Recommended sales price ranges from $649,000–$729,000 per unit at approximately $493–$515/sq ft. Total recommended sales price: $10,604,000."},
  {city:"Los Angeles, CA", desc:"2-story, 5-unit multi-family condo building in Los Angeles with covered parking and a mix of studio, 1-bed, and 2-bed units.", tag:"Multifamily", img:"ten.jpeg", price:"$828K", detail:"A 2-story, 5-unit multi-family condo building in Los Angeles County, built in 1961. The 3,480 sq ft building sits on a 6,367 sq ft lot, zoned LARD. Unit mix: one 2 bed/1 bath ($1,268/mo), two 1 bed/1 bath ($938 and $817/mo), one 1 bed/2 bath ($889/mo), and one studio/1 bath ($778/mo). All units include assigned covered carport parking. Public sewer and water."},
];   

const BUSINESS_LISTINGS = [
  {city:"North Orange County, CA", desc:"2,500 Square Foot Top-Tier Sushi Restaurant for Sale in a stable Orange County market, 100% management run", tag:"For Sale", img:"yukasushi.png", detail:"A rare opportunity to own a thriving, fully management-operated sushi restaurant anchored in an established Orange County commercial district. This 2,500 sq ft turnkey location seats 24 tables and runs on a seasoned team of 13, so ownership stays hands-off from day one. The numbers speak for themselves: $1,451,924 in 2025 gross revenue, $192,765 in cash flow, and $150,775 EBITDA. Fully equipped with a Type 41 liquor license, walk-in cooler, and walk-in freezer. Ideal for an investor or operator seeking a proven, high-volume restaurant with immediate income. Asking $370,000."},
  {city:"North Orange County, CA", desc:"1,200 Square Foot Udon and Korean Comfort-Food Spot", tag:"For Sale", img:"HanNam.jpg", detail:"A high-margin, fast-return Korean bunsik restaurant in a prime Orange County location with excellent Korean and Asian community access. The diverse, crowd-favorite menu — chicken wings, tteokbokki, udon, sushi, and rolls — drives strong, steady traffic. At just 1,200 sq ft with 8 tables and a lean 2-person staff, overhead stays low while returns stay high: $386,179 in 2025 gross income, $101,679 cash flow, and a standout 53% ROI (payback in roughly 1 year 10 months). Monthly rent is a manageable $4,656. A perfect entry point for a first-time owner or a hands-on operator. Asking $195,000."},
  {city:"North Orange County, CA", desc:"High Value Sushi Restaurant in a Stable Local Market", tag:"For Sale", img:"hyori.jpg", detail:"A hard-to-find, authentic sushi restaurant in an established Orange County trade area — the kind of specialty concept that rarely comes to market. Established in 2022, the business generated $828,935 in 2025 gross revenue with $209,079 in cash flow and $61,834 EBITDA. The 1,400 sq ft space runs efficiently with a 3-person team and holds a Type 41 liquor license. Base rent is $5,000 (NNN included), and the kitchen serves a proven lunch-and-dinner schedule (Mon–Fri 11:30 AM–2:30 PM & 5:00–10:30 PM, Sat–Sun 5:00–10:30 PM). A standout opportunity for an operator seeking a niche, loyal-clientele concept. Asking $360,000."},
  {city:"Orange County, CA", desc:"Modernistic Bustling Sushi Restaurant SOLD", tag:"IN ESCROW", img:"sushi1.jpg", detail:"A flagship, high-volume sushi restaurant in Southeast LA County that represented one of the strongest restaurant opportunities in the region. Established in 2015, the business posted $2,347,616 in 2024 gross revenue, $641,433 in cash flow (SDE), and $462,709 EBITDA. The sale included inventory, a 15-person team, a Type 41 liquor license, no CAM charges, and a secure lease running through 2035 at $4,500/month (NNN included). Offered at $1.2M as the owner transitioned into retirement — now successfully sold and under new ownership."},
  {city:"Orange County, CA", desc:"Prime Sushi Franchise/Restaurant in an Up and Coming City", tag:"SOLD", img:"sushi5.jpg", detail:"A thriving sushi restaurant in the sought-after Crystal Cove area, prized for its premium coastal-adjacent location. Established in 2019, the 1,980 sq ft restaurant generated $677,658 in 2025 gross revenue, $80,278 cash flow, and $71,649 EBITDA, supported by a 7-person team and a Type 41 liquor license. With a steady lunch-and-dinner service and base rent of $6,522/month (NNN included), it offered a turnkey path into one of Orange County's most desirable dining markets. Listed at $180,000 — now sold."},
  {city:"Alameda County, CA", desc:"Cozy and popular Japanese-Style Ramen Restaurant SOLD", tag:"SOLD", img:"ramen.jpeg", detail:"A popular, well-established Japanese-style ramen restaurant in a high-traffic Alameda County location with a devoted regular customer base. Known for its rich, slow-simmered broths and an authentic menu that keeps tables full through lunch and dinner, this turnkey operation pairs strong brand recognition with steady, consistent volume. The space is fully built out and equipped, supported by an experienced team, making for a smooth transition to new ownership. A standout opportunity for an operator looking to step into a proven concept in one of the Bay Area's most food-forward markets."},
  {city:"San Bernadino County, CA", desc:"Large sushi and roll restaurant SOLD", tag:"SOLD", img:"sbsushi.jpeg", detail:"A large, high-capacity sushi and roll restaurant occupying a premium commercial space in a thriving San Bernardino County retail corridor. With generous seating, a full sushi bar, and a versatile menu built for both dine-in and to-go volume, the location is positioned to capture strong, steady demand. The spacious build-out offers ample room to grow, anchored by a well-trained staff and excellent visibility, parking, and freeway access. An ideal acquisition for an operator or investor seeking scale in a high-traffic market."},
  {city:"San Francisco County, CA", desc:"Korean-Style traditional culturally innovated restaurant SOLD", tag:"SOLD", img:"sf.jpeg", detail:"A distinctive Korean restaurant in San Francisco County that blends time-honored tradition with bold, modern innovation — a concept built for the city's adventurous dining scene. From rooted, authentic flavors to creative, contemporary presentation, the restaurant has carved out a memorable identity and a strong, engaged customer base. Set in a desirable, walkable San Francisco location, the space is fully equipped and ready for a seamless handoff. A rare chance to own a differentiated, culturally rich concept in one of the country's most competitive and rewarding food markets."}
];

const TEAM = [
  {name:"Alex Ahn", lic:"International Business Network Lead", bio:"", img:"alex.png"},
  {name:"Megan Kim", lic:"Senior Partner", bio:"", img:"megan.png"},
  {name:"David Han", lic:"Partner", bio:"", img:"david.png"},
  {name:"Aiden Lee", lic:"Partner", bio:"", img:"aiden.png"},
  {name:"Edwin Ro", lic:"Senior Partner", bio:"", img:"edwin.png"},
  {name:"Sunny Kim", lic:"Senior Partner", bio:"", img:"sunny.png"},
  {name:"Wendy Huang", lic:"Chinese/Japanese Marketing Team Lead", bio:"", img:"wendy.png"},
  {name:"Moon Hee Chan", lic:"Graphic Engineer", bio:"", img:"moon.png"},
  {name:"Tory Yoon", lic:"Coordinator", bio:"", img:"tory.png"}
];

const CAFE_CHANNELS = [
  {t:"# Homebuyers Lounge", d:"Introduce yourself and ask anything."},
  {t:"# Plumbing", d:"Connect with vetted plumbers and get quotes."},
  {t:"# Interior Design", d:"Ideas, sourcing, and designer consults."},
  {t:"# General Contractors", d:"Renovations, builds, and remodels."},
  {t:"# Lending & Mortgages", d:"Rates, pre-approvals, and loan questions."},
  {t:"# Inspections", d:"Find inspectors and understand reports."},
  {t:"# Landscaping", d:"Yards, hardscape, and curb appeal."},
  {t:"# Off-Topic", d:"Community chat and everything else."}
];

const FAQS = [
  {q:"How much does it cost to work with Realty Peoples?", a:"For buyers, our guidance is typically free — commissions are generally paid through the transaction. For sellers, we'll walk you through our straightforward fee structure during your consultation."},
  {q:"Do I need to be pre-approved before looking at homes?", a:"It's strongly recommended. A pre-approval clarifies your budget and makes your offer far more competitive. We can connect you with trusted lenders in our network."},
  {q:"Which areas do you serve?", a:"Orange County, LA County, and the greater Southern California region — including Fullerton, Irvine, Anaheim, Newport Beach, Pasadena, and more."},
  {q:"What is the Lounge?", a:"A members-only community where buyers and owners chat directly with each other and with service pros — plumbers, designers, contractors, lenders — to ask questions and gather quotes in one place. Free for buyers and owners."},
  {q:"Do you help with commercial property?", a:"Yes. We handle retail, office, and investment opportunities. Reach out through the Contact page and tell us what you're looking for."}
];
