/* ===========================================================================
   SITE DATA — edit these freely. Used by main.js to build page sections.
   =========================================================================== */
const TESTIMONIALS = [
  {q:"They treated our first home like it was their own. Patient, honest, and always a step ahead.", who:"— Former Customer"},
  {q:"We sold above asking and closed without a single surprise. The communication was incredible.", who:"— Former Customer"},
  {q:"More than agents — they felt like family who genuinely wanted us to be happy in our new home.", who:"— Former Customer"}
];

const RESIDENTIAL_LISTINGS = [
  {city:"Gardena, CA", desc:"2 bed · 2.5 bath · 1,281 sqft — Listed at $752K, offering modern living in a prime location. Conveniently close to schools, shopping, dining, and everyday amenities.", tag:"For Sale", img:"gardena.png", price:"$752K", detail:"A sun-filled home with a private courtyard, chef's kitchen, and detached casita. Add full property details here."},
  {city:"Chino, CA", desc:"4 bed · 3.5 bath · 1,930 sqft — Newly built home, a cozy modern estate near top-rated schools and great social hubs.", tag:"In Escrow", img:"nesta.png", price:"$855K", detail:"A spacious great room, a convenient powder room, and a thoughtfully designed kitchen with a center island and adjacent dining area, plus a main-floor bedroom. Add full property details here."},
  {city:"Fontana, CA", desc:"3 bed · 3 bath · 1,677 sqft — Great recently built townhouse, providing great views of California and the San Bernardino Valley.", tag:"Sold", img:"townhouse.png", price:"$532K", detail:"A recently built townhouse with a spacious great room and valley views. Add full property details here."},
  {city:"Diamond Bar, CA", desc:"5 bed · 4 bath · 3,228 sqft — Big, spacious house with great natural lighting in a prime educational location.", tag:"Sold", img:"diamond bar.png", price:"$1.45M", detail:"A large, light-filled home in a top school district. Add full property details here."},
  {city:"Eastvale, CA", desc:"3 bed · 3 bath · 2,655 sqft — Classic craftsman, fully reimagined house with an amazing naturally designed pool.", tag:"Sold", img:"eastvale.png", price:"$950K", detail:"A classic craftsman, fully reimagined, with a beautiful natural pool. Add full property details here."},
  {city:"Fullerton, CA", desc:"4 bed · 3 bath · 2,400 sqft — example listing, edit this text with the real details.", tag:"In Escrow", img:"fullertonn.png", price:"$1.37M", detail:"Longer description shown when someone clicks the card. Add full property details here."}
];

const COMMERCIAL_LISTINGS = [
  {city:"Buena Park, CA", desc:"Prime multi-bay retail plaza in a diverse and high-traffic Buena Park corridor.", tag:"FULLY LEASED", img:"com1.png", detail:"A well-positioned multi-tenant retail plaza in one of Buena Park's busiest commercial corridors, offering excellent street visibility, ample parking, and steady foot traffic. The property featured a flexible row of storefront bays suited to a mix of retail, food, and service tenants, with strong signage exposure and easy freeway access. A turnkey investment opportunity in a dense, established trade area — successfully closed and transferred to new ownership."},
  {city:"Anaheim", desc:"Modern cozy office-suite building in Central Anaheim.", tag:"FULLY LEASED", img:"com2.png", detail:"A clean, modern two-story office building in central Anaheim, configured as a set of efficient professional suites ideal for small businesses, medical, or service tenants. The property offered a bright window-lined facade, a welcoming central entrance, and a practical floor plan that maximized usable space. Located minutes from major thoroughfares with convenient parking, it presented a low-maintenance, income-ready asset — now sold and under new ownership."},
  {city:"Cypress, CA", desc:"Mixed-use officetel building with ground-floor retail in Cypress", tag:"FULLY LEASED", img:"com3.png", detail:" A contemporary officetel tower in Cypress blending professional office floors with ground-level retail — a versatile, mixed-use asset designed for live-work flexibility and dependable rental demand. With multiple stacked floors of suites, strong vertical visibility, and a prime, accessible location, the building offered diverse income streams under one roof. A rare mixed-use opportunity in north Orange County, successfully closed and transferred to its new owner."},
  {city:"Yorba Linda, CA", desc:"Upscale professional center with glass-front tinted suites in Yorba Linda", tag:"FULLY LEASED", img:"com4.png", detail:"A polished professional center in desirable Yorba Linda, combining a glass-curtain main suite with additional flex office space and a refined stone-accented facade. Designed for medical, professional, or boutique service tenants, the property paired modern architecture with practical layouts, generous parking, and attractive landscaping in an affluent, low-vacancy submarket. A standout commercial asset in one of Orange County's most sought-after communities — now sold."}
];

const BUSINESS_LISTINGS = [
  {city:"North Orange County, CA", desc:"2,500 Square Foot Top-Tier Sushi Restaurant for Sale in a stable Orange County market, 100% management run", tag:"For Sale", img:"yukasushi.png", detail:"A rare opportunity to own a thriving, fully management-operated sushi restaurant anchored in an established Orange County commercial district. This 2,500 sq ft turnkey location seats 24 tables and runs on a seasoned team of 13, so ownership stays hands-off from day one. The numbers speak for themselves: $1,451,924 in 2025 gross revenue, $192,765 in cash flow, and $150,775 EBITDA. Fully equipped with a Type 41 liquor license, walk-in cooler, and walk-in freezer. Ideal for an investor or operator seeking a proven, high-volume restaurant with immediate income. Asking $370,000."},
  {city:"North Orange County, CA", desc:"1,200 Square Foot Udon and Korean Comfort-Food Spot", tag:"For Sale", img:"HanNam.jpg", detail:"A high-margin, fast-return Korean bunsik restaurant in a prime Orange County location with excellent Korean and Asian community access. The diverse, crowd-favorite menu — chicken wings, tteokbokki, udon, sushi, and rolls — drives strong, steady traffic. At just 1,200 sq ft with 8 tables and a lean 2-person staff, overhead stays low while returns stay high: $386,179 in 2025 gross income, $101,679 cash flow, and a standout 53% ROI (payback in roughly 1 year 10 months). Monthly rent is a manageable $4,656. A perfect entry point for a first-time owner or a hands-on operator. Asking $195,000."},
  {city:"North Orange County, CA", desc:"High Value Sushi Restaurant in a Stable Local Market", tag:"For Sale", img:"hyori.jpg", detail:"A hard-to-find, authentic sushi restaurant in an established Orange County trade area — the kind of specialty concept that rarely comes to market. Established in 2022, the business generated $828,935 in 2025 gross revenue with $209,079 in cash flow and $61,834 EBITDA. The 1,400 sq ft space runs efficiently with a 3-person team and holds a Type 41 liquor license. Base rent is $5,000 (NNN included), and the kitchen serves a proven lunch-and-dinner schedule (Mon–Fri 11:30 AM–2:30 PM & 5:00–10:30 PM, Sat–Sun 5:00–10:30 PM). A standout opportunity for an operator seeking a niche, loyal-clientele concept. Asking $360,000."},
  {city:"Orange County, CA", desc:"Modernistic Bustling Sushi Restaurant SOLD", tag:"IN ESCROW", img:"sushi1.jpg", detail:"A flagship, high-volume sushi restaurant in Southeast LA County that represented one of the strongest restaurant opportunities in the region. Established in 2015, the business posted $2,347,616 in 2024 gross revenue, $641,433 in cash flow (SDE), and $462,709 EBITDA. The sale included inventory, a 15-person team, a Type 41 liquor license, no CAM charges, and a secure lease running through 2035 at $4,500/month (NNN included). Offered at $1.2M as the owner transitioned into retirement — now successfully sold and under new ownership."},
  {city:"Orange County, CA", desc:"Prime Sushi Franchise/Restaurant in an Up and Coming City", tag:"SOLD", img:"sushi5.jpg", detail:"A thriving sushi restaurant in the sought-after Crystal Cove area, prized for its premium coastal-adjacent location. Established in 2019, the 1,980 sq ft restaurant generated $677,658 in 2025 gross revenue, $80,278 cash flow, and $71,649 EBITDA, supported by a 7-person team and a Type 41 liquor license. With a steady lunch-and-dinner service and base rent of $6,522/month (NNN included), it offered a turnkey path into one of Orange County's most desirable dining markets. Listed at $180,000 — now sold."},
  {city:"Alameda County, CA", desc:"Cozy and popular Japanese-Style Ramen Restaurant SOLD", tag:"SOLD", img:"ramen.jpeg", detail:"A popular, well-established Japanese-style ramen restaurant in a high-traffic Alameda County location with a devoted regular customer base. Known for its rich, slow-simmered broths and an authentic menu that keeps tables full through lunch and dinner, this turnkey operation pairs strong brand recognition with steady, consistent volume. The space is fully built out and equipped, supported by an experienced team, making for a smooth transition to new ownership. A standout opportunity for an operator looking to step into a proven concept in one of the Bay Area's most food-forward markets."},
  {city:"San Bernadino County, CA", desc:"Large sushi and roll restaurant SOLD", tag:"SOLD", img:"sbsushi.jpeg", detail:"A large, high-capacity sushi and roll restaurant occupying a premium commercial space in a thriving San Bernardino County retail corridor. With generous seating, a full sushi bar, and a versatile menu built for both dine-in and to-go volume, the location is positioned to capture strong, steady demand. The spacious build-out offers ample room to grow, anchored by a well-trained staff and excellent visibility, parking, and freeway access. An ideal acquisition for an operator or investor seeking scale in a high-traffic market."},
  {city:"San Francisco County, CA", desc:"Korean-Style traditional culturally innovated restaurant SOLD", tag:"SOLD", img:"sf.jpeg", detail:"A distinctive Korean restaurant in San Francisco County that blends time-honored tradition with bold, modern innovation — a concept built for the city's adventurous dining scene. From rooted, authentic flavors to creative, contemporary presentation, the restaurant has carved out a memorable identity and a strong, engaged customer base. Set in a desirable, walkable San Francisco location, the space is fully equipped and ready for a seamless handoff. A rare chance to own a differentiated, culturally rich concept in one of the country's most competitive and rewarding food markets."}
];

const TEAM = [
  {name:"Alex Ahn", lic:"International Business Network Lead", bio:"", img:"alex.png"},
  {name:"David Han", lic:"Partner", bio:"", img:"david.png"},
  {name:"Aiden Lee", lic:"Partner", bio:"", img:""},
  {name:"Edwin Ro", lic:"Senior Partner", bio:"", img:"edwin.png"},
  {name:"Sunny Kim", lic:"Senior Partner", bio:"", img:"sunny.png"},
  {name:"Wendy Huang", lic:"Chinese/Japanese Marketing Team Lead", bio:"", img:"wendy.png"},
  {name:"Tory Yoon", lic:"Coordinator", bio:"", img:"tory.png"},
  {name:"Megan Kim", lic:"Senior Partner", bio:"", img:"megan.png"}
];

const CAFE_CHANNELS = [
  {t:"# Homebuyers Lounge", d:"Introduce yourself and ask anything."},
  {t:"# Plumbing", d:"Connect with vetted plumbers and get quotes."},
  {t:"# Interior Design", d:"Ideas, sourcing, and designer consults."},
  {t:"# General Contractors", d:"Renovations, builds, and remodels."},
  {t:"# Lending & Mortgages", d:"Rates, pre-approvals, and loan questions."},
  {t:"# Inspections", d:"Find inspectors and understand reports."},
  {t:"# Landscaping", d:"Yards, hardscape, and curb appeal."},
  {t:"# Off-Topic", d:"Community chat and everything else."}
];

const FAQS = [
  {q:"How much does it cost to work with Realty Peoples?", a:"For buyers, our guidance is typically free — commissions are generally paid through the transaction. For sellers, we'll walk you through our straightforward fee structure during your consultation."},
  {q:"Do I need to be pre-approved before looking at homes?", a:"It's strongly recommended. A pre-approval clarifies your budget and makes your offer far more competitive. We can connect you with trusted lenders in our network."},
  {q:"Which areas do you serve?", a:"Orange County, LA County, and the greater Southern California region — including Fullerton, Irvine, Anaheim, Newport Beach, Pasadena, and more."},
  {q:"What is the Lounge?", a:"A members-only community where buyers and owners chat directly with each other and with service pros — plumbers, designers, contractors, lenders — to ask questions and gather quotes in one place. Free for buyers and owners."},
  {q:"Do you help with commercial property?", a:"Yes. We handle retail, office, and investment opportunities. Reach out through the Contact page and tell us what you're looking for."}
];
